trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: meal
  dockerRegistry: docker.io/jayj7568

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build and Push
    pool:
      name: MyPool
      demands:
        - Agent.Name -equals jayRunner
    steps:
    - checkout: self

    - script: |
        echo "Image tag: $(dockerRegistry)/$(imageName):$(tag)"
      displayName: Show full image name

    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(dockerRegistry)/$(imageName):$(tag)

    - script: |
        docker push $(dockerRegistry)/$(imageName):$(tag)
      displayName: Push Docker image
