trigger: none  # Only run manually

parameters:
- name: imageTag
  displayName: Docker Image Tag
  type: string
  default: 'latest'

- name: targetHost
  displayName: Target Server IP or Hostname
  type: string
  default: 'your.server.ip'

- name: sshUser
  displayName: SSH User
  type: string
  default: 'ubuntu'

variables:
  imageName: meal
  dockerRegistry: docker.io/jayj7568

stages:
- stage: Deploy
  displayName: Deploy to Remote Host
  jobs:
  - job: DeployJob
    displayName: Print Docker Image Info
    pool:
      name: MyPool
      demands:
        - Agent.Name -equals jayRunner
    steps:
    - checkout: none

    - script: |
        echo "Image to deploy:"
        echo "$(dockerRegistry)/$(imageName):${{ parameters.imageTag }}"
        echo "Target Host: ${{ parameters.targetHost }}"
        echo "SSH User: ${{ parameters.sshUser }}"
      displayName: Print Parameters
