trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: meal
  dockerRegistry: docker.io/jay7568
  fullImageName: '$(dockerRegistry)/$(imageName):$(tag)'

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build and Push
    pool:
      name: MyPool
      demands:
        - Agent.Name -equals jayRunner
    steps:
    - checkout: self

    - script: |
        echo "Image will be built as: $(fullImageName)"
      displayName: Show full image name

    - script: |
        docker build -t $(fullImageName) .
      displayName: Docker Build

    - script: |
        docker images
      displayName: List Docker Images

    - script: |
        docker push $(fullImageName)
      displayName: Docker Push
